name    'paulnguyen-panfs'
version '0.1.0'
source 'https://github.com/Paul-Nguyen/puppet-panfs'
author 'paulnguyen'
license 'Apache License, Version 2.0'
summary 'Handle Panasas Filesystem config'
description 'Handles the Panasas Filesystem Config'
project_page 'https://github.com/Paul-Nguyen/puppet-panfs'
